### ISSUE TITLE
Missing the --permanent on the RHEL 7 rule in book text

### ISSUE THREAD

**Issue by CalvinHartwell** [abradshaw/getting-started-with-satellite-6-command-line#1]
Hey,

Strangely the --permanent rule is missing in the firewalld rule within the actual book text here, but it is actually within the source code, must be outdated for some reason: 

http://gsw-satellite6.documentation.rocks/installation/index.html

# firewall-cmd --zone=public  --add-service=RH-Satellite-6 \
 --add-service=dhcp --add-service=dns --add-service=tftp

Should be: 

# firewall-cmd --permanent --zone=public  \ 
 --add-service=RH-Satellite-6 --add-service=dhcp \ 
 --add-service=dns --add-service=tftp

Also, for some reason my active zones list was not returning anything within my VM: 

firewall-cmd --get-active-zones

If the active zones list is empty, it seems to be because the NIC has not been assigned to a group: 

 firewall-cmd --zone=public --change-interface=nicInterfaceName

**Comment by abradshaw** [comment]
Ah, thanks for that I shall look into it

**Comment by abradshaw** [comment]
OK, finally managed to get the change to be displayed in the website. I have also added your tip. 

Thanks a lot for letting me know and for the great tip
